### ISSUE TITLE
CLSMatchValue of 256

### ISSUE THREAD

**Issue by drewgilliam** [pubgeo/core3d-metrics#27]
Commit 828f511 introduced a new CLSMatchVaue of "256", where metrics will be checked against all non-zero reference CLS pixels.  

https://github.com/pubgeo/core3d-metrics/blob/f24466dc5dfe9eac48126ef3df42b909638cba16/core3dmetrics/run_geometrics.py#L125-L142

Ground truth files (provided separately) appear to label the CLS ground plane as a non-zero value (typically 2).  So it looks like a CLSMatchValue of 256 will typically evaluate across all pixels, including the ground plane.

@pubgeo - is this expected?

**Comment by pubgeo** [comment]
Yes, it was intentional. The 256 CLS value, which is outside the range of the LAS classification codes, was implemented as a way to allow evaluation against all object identified in the CLS.


We're currently working an update to allow individual and sets of classes evaluated. We plan to allow sets of CLS values to be specified in the config file, such that the metrics (threshold_geometry_metrics and relative_accuracy_metrics) will evaluate and report results for each set of CLS values within a single run.  If you have suggestions on how you would like to see this implemented, please let us know. 

-Andrea

**Comment by drewgilliam** [comment]
So just to confirm, the ground plane (with CLS value of "2") is an "object" that should be evaluated when CLSMatchValue == 256?

As for multiple CLS values - it would be fairly straightforward in a JSON file, where you could define an array of arrays like `'CLSMatchValue': [ [6], [65], [6,65], [256] ]`.  Code would have to loop through the different reference/test CLS match value pairs.

**Comment by pubgeo** [comment]
Yes.  Since the metrics themselves are aimed at man-made features, building, bridge decks, etc, it's not unexpected that ground and other natural features labeled as 0 "Never classified".  The all non-zero CLS option also allows an instance labeled image (NDX) to be used in place of a CLS file.  We can revisit 256 option itself, or add other predefined multi-class options if that's valuable to have.
